INFO     lingkuan_828.conftest:conftest.py:62 [2025-09-01 15:54:03] 用例 test_vps/test_delete.py::TestDeleteUser::test_delete_userlist 开始登录，环境: uat
INFO     lingkuan_828.conftest:conftest.py:100 UAT登录尝试 1/5，MFA验证码: 632098
ERROR    lingkuan_828.conftest:conftest.py:129 第1次登录失败: 登录失败: MFA验证失败
INFO     lingkuan_828.conftest:conftest.py:100 UAT登录尝试 2/5，MFA验证码: 632098
INFO     lingkuan_828.conftest:conftest.py:124 UAT登录成功（第2次尝试）
INFO     lingkuan_828.commons.variable_manager:variable_manager.py:111 [2025-09-01 15:53] 运行时变量已保存到: D:\pycharm_test\lingkuan_828\VAR\runtime_vars_vps.json
INFO     lingkuan_828.commons.api_base:api_base.py:239 [2025-09-01 15:54:15] DELETE请求: /mascontrol/user | 数据: [6868]
INFO     root:test_delete.py:499 第1个账号（ID: 6868）删除接口调用成功
INFO     lingkuan_828.commons.api_base:api_base.py:239 [2025-09-01 15:54:17] DELETE请求: /mascontrol/user | 数据: [6865]
INFO     root:test_delete.py:499 第2个账号（ID: 6865）删除接口调用成功
INFO     lingkuan_828.commons.api_base:api_base.py:239 [2025-09-01 15:54:18] DELETE请求: /mascontrol/user | 数据: [6870]
INFO     root:test_delete.py:499 第3个账号（ID: 6870）删除接口调用成功
INFO     lingkuan_828.commons.api_base:api_base.py:239 [2025-09-01 15:54:20] DELETE请求: /mascontrol/user | 数据: [6864]
INFO     root:test_delete.py:499 第4个账号（ID: 6864）删除接口调用成功
INFO     lingkuan_828.commons.api_base:api_base.py:239 [2025-09-01 15:54:22] DELETE请求: /mascontrol/user | 数据: [6867]
INFO     root:test_delete.py:499 第5个账号（ID: 6867）删除接口调用成功
INFO     lingkuan_828.commons.api_base:api_base.py:239 [2025-09-01 15:54:23] DELETE请求: /mascontrol/user | 数据: [6869]
INFO     root:test_delete.py:499 第6个账号（ID: 6869）删除接口调用成功
INFO     lingkuan_828.commons.api_base:api_base.py:239 [2025-09-01 15:54:25] DELETE请求: /mascontrol/user | 数据: [6866]
INFO     root:test_delete.py:499 第7个账号（ID: 6866）删除接口调用成功
INFO     lingkuan_828.conftest:conftest.py:157 [2025-09-01 15:54:26] 用例 test_vps/test_delete.py::TestDeleteUser::test_delete_userlist 执行完毕