{"name": "平台管理-品种管理-删除品种", "status": "failed", "statusDetails": {"message": "Failed: UAT登录失败（已重试5次）: 登录失败: MFA验证失败", "trace": "登录失败: MFA验证失败\n\nDuring handling of the above exception, another exception occurred:\nUAT登录失败（已重试5次）: 登录失败: MFA验证失败"}, "description": "测试删除用户接口", "attachments": [{"name": "log", "source": "fa2b120f-e7d2-46bb-875d-68dffce5181d-attachment.txt", "type": "text/plain"}], "start": 1759990938850, "stop": 1759990938850, "uuid": "ee7a3462-c886-4005-a108-96f1121e7ab0", "historyId": "8a72f163e05821678a6d0ae1a99f325b", "testCaseId": "8a72f163e05821678a6d0ae1a99f325b", "fullName": "test_vps.test_delete.TestDeleteUser#test_deleteTemplate", "labels": [{"name": "feature", "value": "数据管理-删除VPS测试数据"}, {"name": "parentSuite", "value": "test_vps"}, {"name": "suite", "value": "test_delete"}, {"name": "subSuite", "value": "TestDeleteUser"}, {"name": "host", "value": "DESKTOP-4S9CU1E"}, {"name": "thread", "value": "27828-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_vps.test_delete"}]}