INFO     self_developed_model.conftest:conftest.py:62 [2025-10-09 14:23:59] 用例 test_vps/test_delete.py::TestDeleteUser::test_delete_userlist 开始登录，环境: uat
INFO     self_developed_model.conftest:conftest.py:100 UAT登录尝试 1/5，MFA验证码: 273939
DEBUG    urllib3.connectionpool:connectionpool.py:1051 Starting new HTTPS connection (1): uat.atcp.top:443
DEBUG    urllib3.connectionpool:connectionpool.py:546 https://uat.atcp.top:443 "POST /api/sys/auth/login HTTP/11" 200 None
INFO     self_developed_model.conftest:conftest.py:124 UAT登录成功（第1次尝试）
INFO     self_developed_model.commons.variable_manager:variable_manager.py:111 [2025-10-09 14:20] 运行时变量已保存到: D:\pycharm_test\self_developed_model\VAR\runtime_vars_vps.json
DEBUG    urllib3.connectionpool:connectionpool.py:546 https://uat.atcp.top:443 "DELETE /api/mascontrol/user HTTP/11" 200 None
INFO     self_developed_model.commons.api_base:api_base.py:239 [2025-10-09 14:24:02] DELETE请求: /mascontrol/user | 数据: [8590]
INFO     root:test_delete.py:546 第1个账号（ID: 8590）删除接口调用成功
DEBUG    urllib3.connectionpool:connectionpool.py:546 https://uat.atcp.top:443 "DELETE /api/mascontrol/user HTTP/11" 200 None
INFO     self_developed_model.commons.api_base:api_base.py:239 [2025-10-09 14:24:04] DELETE请求: /mascontrol/user | 数据: [8587]
INFO     root:test_delete.py:546 第2个账号（ID: 8587）删除接口调用成功
DEBUG    urllib3.connectionpool:connectionpool.py:546 https://uat.atcp.top:443 "DELETE /api/mascontrol/user HTTP/11" 200 None
INFO     self_developed_model.commons.api_base:api_base.py:239 [2025-10-09 14:24:06] DELETE请求: /mascontrol/user | 数据: [8592]
INFO     root:test_delete.py:546 第3个账号（ID: 8592）删除接口调用成功
DEBUG    urllib3.connectionpool:connectionpool.py:546 https://uat.atcp.top:443 "DELETE /api/mascontrol/user HTTP/11" 200 None
INFO     self_developed_model.commons.api_base:api_base.py:239 [2025-10-09 14:24:07] DELETE请求: /mascontrol/user | 数据: [8586]
INFO     root:test_delete.py:546 第4个账号（ID: 8586）删除接口调用成功
DEBUG    urllib3.connectionpool:connectionpool.py:546 https://uat.atcp.top:443 "DELETE /api/mascontrol/user HTTP/11" 200 None
INFO     self_developed_model.commons.api_base:api_base.py:239 [2025-10-09 14:24:09] DELETE请求: /mascontrol/user | 数据: [8589]
INFO     root:test_delete.py:546 第5个账号（ID: 8589）删除接口调用成功
DEBUG    urllib3.connectionpool:connectionpool.py:546 https://uat.atcp.top:443 "DELETE /api/mascontrol/user HTTP/11" 200 None
INFO     self_developed_model.commons.api_base:api_base.py:239 [2025-10-09 14:24:10] DELETE请求: /mascontrol/user | 数据: [8591]
INFO     root:test_delete.py:546 第6个账号（ID: 8591）删除接口调用成功
DEBUG    urllib3.connectionpool:connectionpool.py:546 https://uat.atcp.top:443 "DELETE /api/mascontrol/user HTTP/11" 200 None
INFO     self_developed_model.commons.api_base:api_base.py:239 [2025-10-09 14:24:12] DELETE请求: /mascontrol/user | 数据: [8588]
INFO     root:test_delete.py:546 第7个账号（ID: 8588）删除接口调用成功
INFO     self_developed_model.conftest:conftest.py:157 [2025-10-09 14:24:13] 用例 test_vps/test_delete.py::TestDeleteUser::test_delete_userlist 执行完毕