INFO     template.commons.variable_manager:variable_manager.py:40 [2025-09-22 11:13:03] 成功加载静态变量: VAR\uat_data.json
INFO     template.commons.variable_manager:variable_manager.py:64 [2025-09-22 11:13:03] 成功加载运行时变量: VAR\runtime_vars_cloud.json
DEBUG    urllib3.connectionpool:connectionpool.py:1051 Starting new HTTPS connection (1): mt4.mtapi.io:443
DEBUG    urllib3.connectionpool:connectionpool.py:546 https://mt4.mtapi.io:443 "GET /Connect?user=301390786&password=lrd1lff&host=185.96.247.214&port=2333&connectTimeoutSeconds=30 HTTP/11" 201 595
INFO     root:test_openclose.py:55 第1次登录尝试 - 响应内容: {"message":"Not connected in 30000 ms: Starting thread, thread start called","code":"TIMEOUT","stackTrace":"   at TradingAPI.MT4Server.QuoteClient.Connect()\n   at mtrestapi.Connection.ConnectRestore(Int32 user, String password, String host, Int32 port, String id, String hardwareId, Int32 connectTimeoutSeconds) in /src/mt4rest/Controllers/Connection.cs:line 314\n   at mtrestapi.Connection.Connect(Int32 user, String password, String host, Int32 port, String id, String hardwareId, Int32 connectTimeoutSeconds, Boolean downloadOrderHistory) in /src/mt4rest/Controllers/Connection.cs:line 224"}
WARNING  root:test_openclose.py:63 第1次尝试失败 - 无效的token格式: {"message":"Not connected in 30000 ms: Starting thread, thread start called","code":"TIMEOUT","stackTrace":"   at TradingAPI.MT4Server.QuoteClient.Connect()\n   at mtrestapi.Connection.ConnectRestore(Int32 user, String password, String host, Int32 port, String id, String hardwareId, Int32 connectTimeoutSeconds) in /src/mt4rest/Controllers/Connection.cs:line 314\n   at mtrestapi.Connection.Connect(Int32 user, String password, String host, Int32 port, String id, String hardwareId, Int32 connectTimeoutSeconds, Boolean downloadOrderHistory) in /src/mt4rest/Controllers/Connection.cs:line 224"}
INFO     root:test_openclose.py:70 将在5秒后进行第2次重试...
DEBUG    urllib3.connectionpool:connectionpool.py:1051 Starting new HTTPS connection (1): mt4.mtapi.io:443
ERROR    root:test_openclose.py:66 第2次尝试发生异常: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
INFO     root:test_openclose.py:70 将在5秒后进行第3次重试...
DEBUG    urllib3.connectionpool:connectionpool.py:1051 Starting new HTTPS connection (1): mt4.mtapi.io:443
DEBUG    urllib3.connectionpool:connectionpool.py:546 https://mt4.mtapi.io:443 "GET /Connect?user=301390786&password=lrd1lff&host=185.96.247.214&port=2333&connectTimeoutSeconds=30 HTTP/11" 200 None
INFO     root:test_openclose.py:55 第3次登录尝试 - 响应内容: 96151315-f78e-4a68-be25-28182f52fcb8
INFO     root:test_openclose.py:60 第3次尝试成功 - 获取到token: 96151315-f78e-4a68-be25-28182f52fcb8
INFO     root:test_openclose.py:79 登录MT4账号获取token: 96151315-f78e-4a68-be25-28182f52fcb8