{"uuid": "1097576a-a164-416a-ae3b-ae07f3c4222f", "children": ["df93ecc6-52f4-480e-aff3-92d7a8487f35"], "befores": [{"name": "db_transaction", "status": "broken", "statusDetails": {"message": "pymysql.err.InterfaceError: (0, '')\n", "trace": "  File \"D:\\pycharm_test\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\pycharm_test\\venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\pycharm_test\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\pycharm_test\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\pycharm_test\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\pycharm_test\\lingkuan_819\\conftest.py\", line 203, in db_transaction\n    db.commit()  # 替代 rollback()，确保看到其他会话的新数据\n  File \"D:\\pycharm_test\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 482, in commit\n    self._execute_command(COMMAND.COM_QUERY, \"COMMIT\")\n  File \"D:\\pycharm_test\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 843, in _execute_command\n    raise err.InterfaceError(0, \"\")\n"}, "start": 1755564943468, "stop": 1755564943468}], "start": 1755564943468, "stop": 1755564943508}