{"uuid": "34b675ae-593e-4a42-812b-121f45aa6231", "children": ["227ae54d-1fe9-4d9e-83b1-a1602e3698be"], "befores": [{"name": "_xunit_setup_method_fixture_TestCustomerOrders", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestCustomerOrders' object has no attribute 'logger'\n", "trace": "  File \"D:\\python_tools\\python\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\python_tools\\python\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\python_tools\\python\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\python_tools\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\python_tools\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\python_tools\\python\\lib\\site-packages\\_pytest\\python.py\", line 821, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"D:\\python_tools\\python\\lib\\site-packages\\_pytest\\python.py\", line 717, in _call_with_optional_argument\n    func()\n  File \"D:\\pycharm_test\\api_test_framework_refactor\\TestCases\\test_customer_orders.py\", line 26, in setup_method\n    self.logger.info(f\"------------------ 开始执行测试用例 ------------------\")\n"}, "start": 1749205763761, "stop": 1749205763762}], "start": 1749205763761, "stop": 1749205763856}